plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'java-library'
    id 'maven-publish'
    id 'me.modmuss50.mod-publish-plugin' version "${mod_publish_plugin_version}"
}

version = "${mod_version}+${minecraft_version}"
group = maven_group

base {
    archivesName = archives_base_name
}

repositories {
    mavenCentral()

    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = "Jared's maven"
        url = 'https://maven.blamejared.com/'
    }
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
    maven {
        name = 'Shedaniel'
        url = 'https://maven.shedaniel.me/'
    }
    maven {
        url = 'https://maven.nucleoid.xyz'
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }

}

loom {
    def aw = file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath = aw
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
            name = 'Fabric Client'
            ideConfigGenerated = true
            vmArgs '-Dmixin.debug.verbose=true', '-Dmixin.debug.export=true'
        }
        server {
            server()
            name = 'Fabric Server'
            ideConfigGenerated = true
            vmArgs '-Dmixin.debug.verbose=true', '-Dmixin.debug.export=true'
        }
    }
}

sourceSets {
    main {
        java {
            exclude 'umpaz/brewinandchewin/integration/emi/**'
            exclude 'umpaz/brewinandchewin/common/mixin/client/ModelBakeryAccessor.java'
        }
        resources {
            srcDir 'src/generated/resources'
            exclude '**/.cache/**', '**/.cache'
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    runtimeOnly "maven.modrinth:modmenu:${mod_menu_version}"

    compileOnly "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    annotationProcessor "io.github.llamalad7:mixinextras-common:${mixin_extras_version}"
    compileOnly "net.fabricmc:sponge-mixin:${fabric_mixin_version}"
    implementation 'org.jetbrains:annotations:24.1.0'

    implementation("maven.modrinth:farmers-delight-refabricated:${farmers_delight_refabricated_version}") {
        exclude group: 'net.fabricmc'
    }

    compileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    compileOnly "maven.modrinth:appleskin:${appleskin_fabric_version_id}"
    runtimeOnly "maven.modrinth:appleskin:${appleskin_fabric_version_id}"
    compileOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude group: 'net.fabricmc.fabric-api'
    }
    runtimeOnly("me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}") {
        exclude group: 'net.fabricmc.fabric-api'
    }

    compileOnly "maven.modrinth:create-fly:${create_fly_version}"
    runtimeOnly "maven.modrinth:create-fly:${create_fly_version}"

    compileOnly "maven.modrinth:styled-chat:${styled_chat_version}"
    compileOnly "eu.pb4:placeholder-api:${pb4_placeholder_api_version}"

    runtimeOnly "maven.modrinth:styled-chat:${styled_chat_version}"
    runtimeOnly "eu.pb4:predicate-api:${pb4_predicate_api_version}"
    runtimeOnly "eu.pb4:placeholder-api:${pb4_placeholder_api_version}"
    runtimeOnly "me.lucko:fabric-permissions-api:${permissions_api_version}"
    runtimeOnly "eu.pb4:player-data-api:${pb4_player_data_api_version}"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version as int)
    }
    withSourcesJar()
}

def resourceProperties = [
        mod_version                         : mod_version,
        group                               : project.group,
        minecraft_version                   : minecraft_version,
        fabric_api_version                  : fabric_version,
        fabric_loader_version               : loader_version,
        fabric_minecraft_version_range      : fabric_minecraft_version_range,
        fabric_loader_range                 : fabric_loader_range,
        mod_name                            : mod_name,
        fabric_mod_authors                  : mod_authors.split(',').collect { it.trim() }.join('",\n    "'),
        mod_id                              : mod_id,
        mod_license                         : mod_license,
        mod_description                     : mod_description,
        java_version                        : java_version,
        modrinth_page                       : modrinth_page,
        create_fly_fabric_range             : create_fly_fabric_range,
        farmers_delight_refabricated_range  : farmers_delight_refabricated_range,
        HotCocoa                            : '$HotCocoa',
        MilkBottle                          : '$MilkBottle',
        LootParamsBuilderMixin              : '$LootParamsBuilderMixin',
        LootParamsMixin                     : '$LootParamsMixin',
        TipsyCanvasSignRenderMixin          : '$TipsyCanvasSignRenderMixin',
        TipsySignRenderMixin                : '$TipsySignRenderMixin'
]

tasks.withType(ProcessResources).configureEach {
    inputs.properties resourceProperties
    filesMatching(['fabric.mod.json', '*.mixins.json']) {
        expand resourceProperties
    }
    exclude "${mod_id}.cfg"
    exclude '**/.cache/**', '**/.cache'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

tasks.withType(Jar).configureEach {
    from('LICENSE') {
        rename { "${it}_${mod_name}" }
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_name,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : archiveVersion,
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Built-On-Minecraft'      : minecraft_version
        ])
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            artifactId = archives_base_name
            from components.java
        }
    }
}

publishMods {
    file = tasks.named('jar').flatMap { it.archiveFile }
    modLoaders.add 'fabric'
    changelog = rootProject.file('CHANGELOG.md').text
    displayName = "v${mod_version} (Fabric ${minecraft_version})"
    version = "${mod_version}+${minecraft_version}-fabric"
    type = STABLE

    if (modrinth_project_id) {
        modrinth {
            projectId = modrinth_project_id
            accessToken = providers.environmentVariable('MODRINTH_TOKEN')
            minecraftVersions.add minecraft_version
            requires 'fabric-api'
            requires 'farmers-delight-refabricated'
            optional 'create-fly'
            optional 'jei'
            optional 'appleskin'
            optional 'styled-chat'
        }
    }
}
